package com.mycompany.usernavigation;
// Generated Apr 6, 2019, 3:20:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="gitTask"
)
public class User  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String middleName;
     private String lastName;
     private String emai;

    public User() {
    }

	
    public User(int id) {
        this.id = id;
    }
    public User(int id, String firstName, String middleName, String lastName, String emai) {
       this.id = id;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.emai = emai;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="middle_name", length=45)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="emai", length=45)
    public String getEmai() {
        return this.emai;
    }
    
    public void setEmai(String emai) {
        this.emai = emai;
    }




}


